---
title: "Reproducibility"
author: "Claudiu Forgaci"
---

## Workshop

### Introduction (30 minutes)
Instructor: Claudiu

- welcome and schedule
- relevance of repro and autom
- discussion: what kind of methods do you use to document a project? (notes on a board)
- review a few cases of irreproducibility; see exmaples here: https://github.com/Reproducible-Science-Curriculum/Reproducible-Science-Hackathon-Dec-08-2014/wiki/Irreproducible-Examples
- There isn't time for an exercise

### File organisation
Instructor: Barbara

### Automation
Instructor: Barbara

### Literate programming
Instructor: Claudiu

- [Getting started with R Markdown (episode part of the R for Social Scientists Data Carpentry curriculum)](https://datacarpentry.org/r-socialsci/05-rmarkdown/index.html) - 1 hour

- [ ] Transfer the content of the Automation part to an R Markdown

### Publishing
Instructor: Claudiu

- "Sharing, publishing, archiving" workshop material by Karen Cranston and Hilmar Lapp: [lesson](https://github.com/Reproducible-Science-Curriculum/rr-publication) and [slides](https://reproducible-science-curriculum.github.io/2015-06-01-reproducible-science-idigbio/slides/01-publication-slides.html#/)
  
  - 

  + FAIR data and software facilitates reproducibility
  + End with an overview of the steps of a publication process

- Preparing the R Markdown document from the previous part for publication

- 

## ReproHack

## Challenge

---

## Definitions

-   Reproducible vs. Replicable vs. Robust vs. Generalisable (see The Turing Way)

## File organisation

## Testing

## Reproducible computational environments

## Resources

-   [R Workflow](http://hbiostat.org/rflow)
-   [The Turing Way handbook to reproducible, ethical and collaborative data science - Guide for Reproducible Research](https://the-turing-way.netlify.app/reproducible-research/reproducible-research.html)
-   [Reproducible Research Data and Project Management in R](https://annakrystalli.me/rrresearchACCE20/)
-   [The `holepunch` package](https://github.com/karthik/holepunch)
-   [`rrtools`: Tools for Writing Reproducible Research in R](https://github.com/benmarwick/rrtools)

## References
